# Generated by Django 3.1.1 on 2020-11-11 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shuzhi', '0003_auto_20201111_2114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shuzhizhe',
            options={'ordering': ('addr',), 'verbose_name': '述职者', 'verbose_name_plural': '述职者'},
        ),
        migrations.RemoveField(
            model_name='shuzhizhe',
            name='order',
        ),
        migrations.AlterField(
            model_name='shuzhizhe',
            name='addr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shuzhi.addr', verbose_name='所属营区'),
        ),
    ]
