# Generated by Django 3.1.1 on 2020-11-11 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuzhi', '0004_auto_20201111_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shuzhizhe',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, '未述职，前来述职'), (1, '未述职，以后述职'), (2, '述职完毕')], default=0, null=True, verbose_name='状态'),
        ),
    ]
