# Generated by Django 3.1.1 on 2020-11-15 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuzhi', '0005_auto_20201112_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shuzhizhe',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, '未述职，前来述职'), (1, '未述职，下次述职'), (2, '述职完毕')], default=1, null=True, verbose_name='状态'),
        ),
    ]
