# Generated by Django 3.1.1 on 2020-11-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuzhi', '0006_auto_20201115_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shuzhizhe',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='姓名'),
        ),
    ]
